import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    home: "Home",
    wishlist: "Wishlist",
    cart: "Cart",
    login: "Login",
    logout: "Logout",
    search_placeholder: "Search for products, brands and more",
    dashboard: "My Dashboard",
    admin_panel: "Admin Panel",
    logo_tagline: "Explore Plus",
    // Home
    featured_products: "Featured Products",
    view_all: "View All",
    trending_now: "Trending Now",
    best_deals: "Best Deals Today",
    flash_sale: "Flash Sale",
    fashion_week: "Fashion Week",
    home_deals: "Home Deals",
    electronics_offer: "Upto 70% off Electronics",
    fashion_offer: "Top Brands, Great Prices",
    home_offer: "Upgrade Your Space",
    shop_now: "Shop Now",
    explore: "Explore",
    discover: "Discover",
    ends_in: "Ends in",
    offer_ended: "Offer Ended",
    loading_shop: "Loading premium shopping experience...",
    about: "ABOUT",
    help: "HELP",
    policy: "POLICY",
    connect: "CONNECT",
    about_us: "About Us",
    careers: "Careers",
    press: "Press",
    blog: "Blog",
    payments: "Payments",
    shipping: "Shipping",
    return_policy: "Return Policy",
    faq: "FAQ",
    privacy: "Privacy",
    terms: "Terms of Use",
    security: "Security",
    sitemap: "Sitemap",
    rights_reserved: "All Rights Reserved",
    // Shop
    shop_title: "Shop our Premium Collection",
    search_products: "Search products...",
    all_categories: "All Categories",
    filters: "Filters",
    min_price: "Min Price",
    max_price: "Max Price",
    sort_by: "Sort By",
    sort_default: "Default Sort",
    price_low_high: "Price: Low to High",
    price_high_low: "Price: High to Low",
    discount_high_low: "Discount: High to Low",
    clear_filters: "Clear Filters",
    found_products: "Found {count} products",
    add_to_cart: "Add to Cart",
    out_of_stock: "Out of Stock",
    // Product Detail
    category: "Category",
    add_wishlist: "Add to Wishlist",
    remove_wishlist: "Remove from Wishlist",
    quantity: "Quantity",
    description: "Description",
    specifications: "Specifications",
    reviews: "Reviews",
    back_to_shop: "Back to Shop",
    // Cart
    shopping_cart: "Shopping Cart",
    cart_empty: "Your cart is empty",
    start_shopping: "Start Shopping",
    price: "Price",
    total: "Total",
    remove: "Remove",
    subtotal: "Subtotal",
    discount: "Discount",
    grand_total: "Grand Total",
    proceed_checkout: "Proceed to Checkout",
    order_summary: "Order Summary",
    items_count: "Items",
    // Checkout
    checkout: "Checkout",
    billing_details: "Billing Details",
    full_name: "Full Name",
    email_address: "Email Address",
    phone_number: "Phone Number",
    shipping_address: "Shipping Address",
    payment_method: "Payment Method",
    cash_on_delivery: "Cash on Delivery",
    credit_card: "Credit / Debit Card",
    upi: "UPI (Paytm/GPay)",
    place_order: "Place Order",
    order_placed_success: "Order Placed Successfully!",
    thank_you_order: "Thank you for shopping with Sakthi Shop.",
    order_id: "Order ID",
    track_order: "You can track your order in your dashboard.",
    back_home: "Back to Home",
    // Login / Signup
    welcome_back: "Welcome Back",
    login_sub: "Login to access your dashboard, orders & wishlist",
    password: "Password",
    no_account: "Don't have an account?",
    signup_now: "Sign Up Now",
    create_account: "Create Account",
    signup_sub: "Join Sakthi Shop to explore a curated premium experience",
    confirm_password: "Confirm Password",
    already_member: "Already a member?",
    login_now: "Login Now",
    // User Dashboard
    my_profile: "My Profile",
    personal_info: "Personal Information",
    my_orders: "My Orders",
    role: "Role",
    joined_on: "Joined on",
    no_orders: "You have not placed any orders yet.",
    order_date: "Date",
    status: "Status",
    items: "Items",
    // Admin
    admin_dashboard: "Admin Dashboard",
    manage_products: "Manage Products",
    manage_banners: "Manage Banners",
    add_product: "Add New Product",
    edit_product: "Edit Product",
    product_name: "Product Name",
    product_price: "Price ($)",
    product_discount: "Discount (%)",
    product_description: "Description",
    product_category: "Category",
    product_stock: "Stock Quantity",
    product_image: "Product Image URL or Upload File",
    save: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    actions: "Actions",
    banner_title: "Banner Title",
    banner_subtitle: "Banner Subtitle",
    banner_cta: "CTA Button Text",
    banner_duration: "Duration (sec)",
    banner_bg: "Background Style (CSS)",
    banner_emoji: "Banner Emoji",
    banner_expiry: "Expiry Time (Optional)",
    add_banner: "Add Banner",
    edit_banner: "Edit Banner",
  },
  ta: {
    // Navbar
    home: "முகப்பு",
    wishlist: "விருப்பப் பட்டியல்",
    cart: "கூடை",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    search_placeholder: "தயாரிப்புகள், பிராண்டுகள் மற்றும் பலவற்றைத் தேடுங்கள்",
    dashboard: "எனது டாஷ்போர்டு",
    admin_panel: "நிர்வாகக் குழு",
    logo_tagline: "எக்ஸ்ப்ளோர் பிளஸ்",
    // Home
    featured_products: "சிறப்புத் தயாரிப்புகள்",
    view_all: "அனைத்தையும் காட்டு →",
    trending_now: "இப்போது பிரபலமாக உள்ளவை",
    best_deals: "இன்றைய சிறந்த சலுகைகள்",
    flash_sale: "மின்னல் விற்பனை",
    fashion_week: "ஃபேஷன் வாரம்",
    home_deals: "வீட்டு உபயோக சலுகைகள்",
    electronics_offer: "மின்னணு சாதனங்களுக்கு 70% வரை தள்ளுபடி",
    fashion_offer: "சிறந்த பிராண்டுகள், சிறந்த விலைகள்",
    home_offer: "உங்கள் இடத்தை மேம்படுத்துங்கள்",
    shop_now: "இப்போதே வாங்குங்கள்",
    explore: "ஆராய்ந்து பாருங்கள்",
    discover: "கண்டறியுங்கள்",
    ends_in: "முடிவடைகிறது",
    offer_ended: "சலுகை முடிவடைந்தது",
    loading_shop: "பிரீமியம் ஷாப்பிங் அனுபவத்தை ஏற்றுகிறது...",
    about: "எங்களைப் பற்றி",
    help: "உதவி",
    policy: "கொள்கை",
    connect: "தொடர்பு கொள்ள",
    about_us: "எங்களைப் பற்றி",
    careers: "வேலை வாய்ப்புகள்",
    press: "செய்தி ஊடகம்",
    blog: "வலைப்பதிவு",
    payments: "பணப்பரிவர்த்தனை",
    shipping: "ஷிப்பிங்",
    return_policy: "திரும்பப் பெறும் கொள்கை",
    faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    privacy: "தனியுரிமை",
    terms: "பயன்பாட்டு விதிமுறைகள்",
    security: "பாதுகாப்பு",
    sitemap: "தளவரைபடம்",
    rights_reserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
    // Shop
    shop_title: "எங்கள் பிரீமியம் சேகரிப்பை வாங்குங்கள்",
    search_products: "தயாரிப்புகளைத் தேடுங்கள்...",
    all_categories: "அனைத்து பிரிவுகளும்",
    filters: "வடிகட்டிகள்",
    min_price: "குறைந்தபட்ச விலை",
    max_price: "அதிகபட்ச விலை",
    sort_by: "வரிசைப்படுத்து",
    sort_default: "இயல்புநிலை வரிசை",
    price_low_high: "விலை: குறைந்ததிலிருந்து அதிகம்",
    price_high_low: "விலை: அதிகத்திலிருந்து குறைவு",
    discount_high_low: "தள்ளுபடி: அதிகத்திலிருந்து குறைவு",
    clear_filters: "வடிகட்டிகளை நீக்கு",
    found_products: "{count} தயாரிப்புகள் கண்டறியப்பட்டன",
    add_to_cart: "கூடையில் சேர்",
    out_of_stock: "இருப்பு இல்லை",
    // Product Detail
    category: "பிரிவு",
    add_wishlist: "விருப்பப் பட்டியலில் சேர்",
    remove_wishlist: "விருப்பப் பட்டியலிலிருந்து நீக்கு",
    quantity: "அளவு",
    description: "விளக்கம்",
    specifications: "விவரக்குறிப்புகள்",
    reviews: "மதிப்புரைகள்",
    back_to_shop: "கடைக்குத் திரும்பு",
    // Cart
    shopping_cart: "ஷாப்பிங் கூடை",
    cart_empty: "உங்கள் கூடை காலியாக உள்ளது",
    start_shopping: "ஷாப்பிங் செய்யத் தொடங்குங்கள்",
    price: "விலை",
    total: "மொத்தம்",
    remove: "நீக்கு",
    subtotal: "துணைத் தொகை",
    discount: "தள்ளுபடி",
    grand_total: "மொத்தத் தொகை",
    proceed_checkout: "பணம் செலுத்தச் செல்லுங்கள்",
    order_summary: "ஆர்டர் சுருக்கம்",
    items_count: "பொருட்கள்",
    // Checkout
    checkout: "செக்அவுட்",
    billing_details: "பில்லிங் விவரங்கள்",
    full_name: "முழு பெயர்",
    email_address: "மின்னஞ்சல் முகவரி",
    phone_number: "தொலைபேசி எண்",
    shipping_address: "ஷிப்பிங் முகவரி",
    payment_method: "பணப்பரிவர்த்தனை முறை",
    cash_on_delivery: "டெலிவரியின் போது பணம் செலுத்துதல்",
    credit_card: "கிரெடிट / டெபிட் கார்டு",
    upi: "UPI (Paytm/GPay)",
    place_order: "ஆர்டர் செய்யுங்கள்",
    order_placed_success: "ஆர்டர் வெற்றிகரமாக செய்யப்பட்டது!",
    thank_you_order: "சக்தி ஷாப்பில் ஷாப்பிங் செய்ததற்கு நன்றி.",
    order_id: "ஆர்டர் ஐடி",
    track_order: "உங்கள் டாஷ்போர்டில் உங்கள் ஆர்டரைக் கண்காணிக்கலாம்.",
    back_home: "முகப்பிற்குத் திரும்பு",
    // Login / Signup
    welcome_back: "நல்வரவு",
    login_sub: "உங்கள் டாஷ்போர்டு, ஆர்டர்கள் மற்றும் விருப்பப்பட்டியலை அணுக உள்நுழையவும்",
    password: "கடவுச்சொல்",
    no_account: "உங்களிடம் கணக்கு இல்லையா?",
    signup_now: "இப்போது பதிவு செய்க",
    create_account: "கணக்கை உருவாக்கு",
    signup_sub: "கியூரேட்டட் பிரீமியம் அனுபவத்தை ஆராய சக்தி ஷாப்பில் இணையுங்கள்",
    confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்துக",
    already_member: "ஏற்கனவே உறுப்பினரா?",
    login_now: "இப்போது உள்நுழையவும்",
    // User Dashboard
    my_profile: "எனது சுயவிவரம்",
    personal_info: "தனிப்பட்ட விவரங்கள்",
    my_orders: "எனது ஆர்டர்கள்",
    role: "பங்கு",
    joined_on: "இணைந்த தேதி",
    no_orders: "நீங்கள் இன்னும் எந்த ஆர்டரையும் செய்யவில்லை.",
    order_date: "தேதி",
    status: "நிலை",
    items: "பொருட்கள்",
    // Admin
    admin_dashboard: "நிர்வாக டாஷ்போர்டு",
    manage_products: "தயாரிப்புகளை நிர்வகி",
    manage_banners: "பேனர்களை நிர்வகி",
    add_product: "புதிய தயாரிப்பைச் சேர்",
    edit_product: "தயாரிப்பைத் திருத்து",
    product_name: "தயாரிப்பு பெயர்",
    product_price: "விலை ($)",
    product_discount: "தள்ளுபடி (%)",
    product_description: "விளக்கம்",
    product_category: "பிரிவு",
    product_stock: "இருப்பு அளவு",
    product_image: "தயாரிப்பு படம் URL அல்லது கோப்பை பதிவேற்றவும்",
    save: "மாற்றங்களைச் சேமி",
    cancel: "ரத்து செய்",
    delete: "நீக்கு",
    actions: "செயல்கள்",
    banner_title: "பேனர் தலைப்பு",
    banner_subtitle: "பேனர் துணைத்தலைப்பு",
    banner_cta: "பொத்தான் உரை (CTA)",
    banner_duration: "கால அளவு (விநாடிகள்)",
    banner_bg: "பின்னணி நடை (CSS)",
    banner_emoji: "பேனர் எமோஜி",
    banner_expiry: "காலாவதி நேரம் (விரும்பினால்)",
    add_banner: "பேனர் சேர்",
    edit_banner: "பேனரைத் திருத்து",
  },
  hi: {
    // Navbar
    home: "होम",
    wishlist: "विशलिस्ट",
    cart: "कार्ट",
    login: "लॉगिन",
    logout: "लॉगआउट",
    search_placeholder: "उत्पाद, ब्रांड और बहुत कुछ खोजें",
    dashboard: "मेरा डैशबोर्ड",
    admin_panel: "एडमिन पैनल",
    logo_tagline: "एक्सप्लोर प्लस",
    // Home
    featured_products: "विशेष रुप से प्रदर्शित उत्पाद",
    view_all: "सभी देखें →",
    trending_now: "अभी ट्रेंडिंग में",
    best_deals: "आज की सर्वश्रेष्ठ डील",
    flash_sale: "फ्लैश सेल",
    fashion_week: "फैशन वीक",
    home_deals: "होम डील्स",
    electronics_offer: "इलेक्ट्रॉनिक्स पर 70% तक की छूट",
    fashion_offer: "शीर्ष ब्रांड, बेहतरीन कीमतें",
    home_offer: "अपने स्थान को अपग्रेड करें",
    shop_now: "अभी खरीदें",
    explore: "एक्सप्लोर करें",
    discover: "खोजें",
    ends_in: "समाप्त होने में",
    offer_ended: "ऑफ़र समाप्त",
    loading_shop: "प्रीमियम शॉपिंग अनुभव लोड हो रहा है...",
    about: "हमारे बारे में",
    help: "सहायता",
    policy: "नीति",
    connect: "संपर्क करें",
    about_us: "हमारे बारे में",
    careers: "करियर",
    press: "प्रेस",
    blog: "ब्लॉग",
    payments: "भुगतान",
    shipping: "शिपिंग",
    return_policy: "वापसी नीति",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    privacy: "गोपनीयता",
    terms: "उपयोग की शर्तें",
    security: "सुरक्षा",
    sitemap: "साइटमैप",
    rights_reserved: "सर्वाधिकार सुरक्षित",
    // Shop
    shop_title: "हमारे प्रीमियम संग्रह की खरीदारी करें",
    search_products: "उत्पाद खोजें...",
    all_categories: "सभी श्रेणियां",
    filters: "फ़िल्टर",
    min_price: "न्यूनतम मूल्य",
    max_price: "अधिकतम मूल्य",
    sort_by: "क्रमबद्ध करें",
    sort_default: "डिफ़ॉल्ट क्रम",
    price_low_high: "कीमत: कम से अधिक",
    price_high_low: "कीमत: अधिक से कम",
    discount_high_low: "छूट: अधिक से कम",
    clear_filters: "फ़िल्टर हटाएं",
    found_products: "{count} उत्पाद मिले",
    add_to_cart: "कार्ट में जोड़ें",
    out_of_stock: "आउट ऑफ स्टॉक",
    // Product Detail
    category: "श्रेणी",
    add_wishlist: "विशलिस्ट में जोड़ें",
    remove_wishlist: "विशलिस्ट से हटाएं",
    quantity: "मात्रा",
    description: "विवरण",
    specifications: "विशेष विवरण",
    reviews: "समीक्षाएं",
    back_to_shop: "दुकान पर वापस जाएं",
    // Cart
    shopping_cart: "शॉपिंग कार्ट",
    cart_empty: "आपकी कार्ट खाली है",
    start_shopping: "खरीदारी शुरू करें",
    price: "कीमत",
    total: "कुल",
    remove: "हटाएं",
    subtotal: "उप-योग",
    discount: "छूट",
    grand_total: "कुल योग",
    proceed_checkout: "चेकआउट के लिए आगे बढ़ें",
    order_summary: "ऑर्डर सारांश",
    items_count: "आइटम",
    // Checkout
    checkout: "चेकआउट",
    billing_details: "बिलिंग विवरण",
    full_name: "पूरा नाम",
    email_address: "ईमेल पता",
    phone_number: "फ़ोन नंबर",
    shipping_address: "शिपिंग का पता",
    payment_method: "भुगतान का प्रकार",
    cash_on_delivery: "कैश ऑन डिलीवरी",
    credit_card: "क्रेडिट / डेबिट कार्ड",
    upi: "UPI (Paytm/GPay)",
    place_order: "ऑर्डर करें",
    order_placed_success: "ऑर्डर सफलतापूर्वक सबमिट हो गया!",
    thank_you_order: "सकती शॉप पर खरीदारी के लिए धन्यवाद।",
    order_id: "ऑर्डर आईडी",
    track_order: "आप अपने डैशबोर्ड में अपना ऑर्डर ट्रैक कर सकते हैं।",
    back_home: "होम पर वापस जाएं",
    // Login / Signup
    welcome_back: "स्वागत हे",
    login_sub: "अपने डैशबोर्ड, ऑर्डर और विशलिस्ट तक पहुंचने के लिए लॉगिन करें",
    password: "पासवर्ड",
    no_account: "क्या आपका कोई खाता नहीं है?",
    signup_now: "अभी साइन अप करें",
    create_account: "खाता बनाएं",
    signup_sub: "एक क्यूरेटेड प्रीमियम अनुभव का पता लगाने के लिए सकती शॉप से जुड़ें",
    confirm_password: "पासवर्ड की पुष्टि करें",
    already_member: "क्या आप पहले से सदस्य हैं?",
    login_now: "अभी लॉगिन करें",
    // User Dashboard
    my_profile: "मेरी प्रोफाइल",
    personal_info: "व्यक्तिगत जानकारी",
    my_orders: "मेरे ऑर्डर",
    role: "भूमिका",
    joined_on: "शामिल होने की तिथि",
    no_orders: "आपने अभी तक कोई ऑर्डर नहीं दिया है।",
    order_date: "दिनांक",
    status: "स्थिति",
    items: "आइटम",
    // Admin
    admin_dashboard: "एडमिन डैशबोर्ड",
    manage_products: "उत्पाद प्रबंधित करें",
    manage_banners: "बैनर प्रबंधित करें",
    add_product: "नया उत्पाद जोड़ें",
    edit_product: "उत्पाद संपादित करें",
    product_name: "उत्पाद का नाम",
    product_price: "कीमत ($)",
    product_discount: "छूट (%)",
    product_description: "विवरण",
    product_category: "श्रेणी",
    product_stock: "स्टॉक मात्रा",
    product_image: "उत्पाद छवि URL या फ़ाइल अपलोड करें",
    save: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    actions: "कार्रवाई",
    banner_title: "बैनर शीर्षक",
    banner_subtitle: "बैनर उपशीर्षक",
    banner_cta: "बटन का नाम (CTA)",
    banner_duration: "अवधि (सेकंड)",
    banner_bg: "पृष्ठभूमि शैली (CSS)",
    banner_emoji: "बैनर इमोजी",
    banner_expiry: "समाप्ति समय (वैकल्पिक)",
    add_banner: "बैनर जोड़ें",
    edit_banner: "बैनर संपादित करें",
  }
};

export const languages = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' }
];

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('sakthi_shop_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('sakthi_shop_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, replacements = {}) => {
    const translationSet = translations[lang] || translations['en'];
    let text = translationSet[key] || translations['en'][key] || key;
    
    // Replace tokens like {count}
    Object.keys(replacements).forEach(token => {
      text = text.replace(`{${token}}`, replacements[token]);
    });
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
